# Specify version format
version: "{build}"

# specify custom environment variables
environment:
  # We cannot use LLVM toolset for now because the boost installed on the server is built not for LLVM.
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
#    - image: Visual Studio 2017
#      GENERATOR: Visual Studio 15 2017
#      LLVM_TOOLCHAIN: LLVM-vs2015
#      platform: Win32
      
#    - image: Visual Studio 2017
#      GENERATOR: Visual Studio 15 2017
#      LLVM_TOOLCHAIN: LLVM-vs2015
#      platform: Win32
      
    - image: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015
      LLVM_TOOLCHAIN: LLVM-vs2014
      platform: Win32

    - image: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015 Win64
      LLVM_TOOLCHAIN: LLVM-vs2014
      platform: x64

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\dart

# branches to build
branches:
  # whitelist
  # only: 
  #   - master
  # blacklist
  except:
    - gh-pages

# scripts that run after cloning repository
install:
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows

  # clone vcpkg
  - cd C:\projects
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  
  # build vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
 
  # install pacakges
  # ---- required dependencies: boost, eigen3, libccd, fcl, assimp
  - vcpkg install boost:%VCPKG_ARCH%
  - vcpkg install eigen3:%VCPKG_ARCH%
  - vcpkg install ccd:%VCPKG_ARCH%
  - vcpkg install fcl:%VCPKG_ARCH%
  - vcpkg install assimp:%VCPKG_ARCH%
  # ---- optional dependencies: nlopt, ipopt, bullet3, ode, flann, tinyxml2, urdfdom_headers, urdfdom, opengl, freeglut, osg
  #- vcpkg install nlopt:%VCPKG_ARCH%
  #- vcpkg install ipopt:%VCPKG_ARCH%
  #- vcpkg install bullet3:%VCPKG_ARCH%
  #- vcpkg install ode:%VCPKG_ARCH%
  #- vcpkg install flann:%VCPKG_ARCH%
  #- vcpkg install tinyxml2:%VCPKG_ARCH%
  #- vcpkg install urdfdom_headers:%VCPKG_ARCH%
  #- vcpkg install urdfdom:%VCPKG_ARCH%
  #- vcpkg install opengl:%VCPKG_ARCH%
  #- vcpkg install freeglut:%VCPKG_ARCH%
  #- vcpkg install osg:%VCPKG_ARCH%
  
  - vcpkg integrate install

  - cmd: cd C:\projects\dart
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" "-DCMAKE_TOOLCHAIN_FILE=C:\projects\vcpkg\scripts\buildsystems\vcpkg.cmake" -T"%LLVM_TOOLCHAIN%" ..
  
# preserve contents of selected directories and files across project builds
cache:
  - C:\projects\vcpkg\installed -> .appveyor.yml
  - C:\projects\vcpkg\packages -> .appveyor.yml

build:
  project: C:\projects\dart\build\dart.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: minimal                       # MSBuild verbosity level (quiet|minimal|normal|detailed)

#test_script:
  #- cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure
